import json

from src.data.registry import DataRegistry
from src.llm.backend import (
    StubLLMBackend,
)
from src.llm.conditions import (
    generate_c1,
    generate_c2,
)
from src.llm.generator import (
    ProposalGenerator,
)
from src.llm.prompt_builder import (
    build_proposal_prompt,
)
from src.llm.proposal_parser import (
    parse_proposal,
)
from src.llm.proposal_validator import (
    classify_hallucination,
    validate_proposal_authority,
    validate_proposal_schema,
)
from src.rag.models import (
    RagChunk,
    RetrievalResult,
)


def _bom():
    return {
        "parts": [
            {
                "part_id": "PILOT_001",
                "name": "Pedal box mounting bracket",
                "material_id": "AL_6061_T6",
                "process_id": "CNC_MILLING",
            }
        ]
    }


def _response():
    return json.dumps({
        "proposal_id": "TEST_PROP_001",
        "part_id": "PILOT_001",
        "change_type": "material",
        "target_field": "material_id",
        "old_value": "AL_6061_T6",
        "new_value": "AL_7075_T6",
        "reasoning_summary": "Conservative canonical identifier test proposal.",
    })


class DummyRetriever:
    def __init__(self):
        self.calls = []

    def retrieve(
        self,
        query,
        top_k=5,
        filters=None,
    ):
        self.calls.append({
            "query": query,
            "top_k": top_k,
            "filters": filters,
        })
        chunk = RagChunk(
            chunk_id="chunk_TEST",
            document_id="doc_TEST",
            text="Rule ID: S_3.5.12 evidence",
            source_type="fsg_rule",
            source_id="FSG_RULES_2026",
            source_reference="S 3.5.12, p.115",
            metadata={"rule_id": "S_3.5.12"},
        )
        return [
            RetrievalResult(
                chunk=chunk,
                score=1.0,
                rank=1,
            )
        ]


def _status(name, passed):
    print(
        f"{name}: {'PASS' if passed else 'FAIL'}"
    )
    if not passed:
        raise SystemExit(1)


def main():
    bom = _bom()
    part = bom["parts"][0]
    registry = DataRegistry()
    backend = StubLLMBackend(
        _response()
    )
    generator = ProposalGenerator(
        backend,
        registry=registry,
    )
    retriever = DummyRetriever()

    prompt = build_proposal_prompt(
        bom,
        part,
        registry,
    )
    parsed = parse_proposal(
        _response()
    )
    schema = validate_proposal_schema(
        parsed
    )
    authority = validate_proposal_authority(
        parsed,
        bom,
        registry=registry,
    )
    hallucination = classify_hallucination(
        True,
        schema,
        authority,
    )
    c1 = generate_c1(
        generator,
        bom=bom,
        target_part=part,
        seed=0,
    )
    c2 = generate_c2(
        generator,
        bom=bom,
        target_part=part,
        retriever=retriever,
        seed=0,
    )

    print("=" * 70)
    print("A10 — LLM PIPELINE SOFTWARE VALIDATION")
    print("=" * 70)
    print("NO THESIS LLM RESULTS GENERATED BY THIS SCRIPT")
    print("-" * 70)

    _status(
        "Prompt builder",
        "SYSTEM ROLE" in prompt.prompt
        and "OUTPUT INSTRUCTIONS" in prompt.prompt,
    )
    _status(
        "JSON parser",
        parsed["proposal_id"] == "TEST_PROP_001",
    )
    _status(
        "Schema validator",
        schema["schema_valid"],
    )
    _status(
        "Authority validator",
        authority["authority_valid"],
    )
    _status(
        "Hallucination classifier",
        hallucination["hallucinated"] is False,
    )
    _status(
        "C1 no-RAG isolation",
        c1["retrieval"]["rag_enabled"] is False,
    )
    _status(
        "C2 RAG integration",
        c2["retrieval"]["rag_enabled"] is True
        and retriever.calls[0]["top_k"] == 5,
    )
    _status(
        "Trace logging",
        bool(c2["raw_output"])
        and bool(c2["prompt_hash"])
        and "chain_of_thought" not in c2,
    )

    print("\nA10 SOFTWARE VALIDATION: PASS")


if __name__ == "__main__":
    main()
